
name: Build PR
on:
  pull_request_target:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: pull-request
    name: build astro
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build astro
        shell: 'bash'
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_BRANCH: main
        run: |
          yarn install
          yarn run build
